import { accentPalette, semanticColorNames, thomDesignTokens } from "./index";

export function renderTailwindTheme(): string {
  const { color, typography, easing, effect } = thomDesignTokens;
  const colors: Array<[string, string]> = [
    ["background", color.background],
    ["surface", color.surface],
    ["surface-foreground", color.surfaceForeground],
    ["surface-raised", color.surfaceRaised],
    ["surface-raised-foreground", color.surfaceRaisedForeground],
    ["card", color.card],
    ["card-foreground", color.cardForeground],
    ["hover-card", color.hoverCard],
    ["hover-card-foreground", color.hoverCardForeground],
    ["popover", color.popover],
    ["popover-foreground", color.popoverForeground],
    ["dialog", color.dialog],
    ["dialog-foreground", color.dialogForeground],
    ["scrim", color.scrim],
    ["foreground", color.foreground],
    ["foreground-strong", color.foregroundStrong],
    ["foreground-muted", color.foregroundMuted],
    ["foreground-subtle", color.foregroundSubtle],
    ["foreground-inverse", color.foregroundInverse],
    ["border", color.border],
    ["border-strong", color.borderStrong],
    ["input", color.input],
    ["ring", color.ring],
    ["brand", color.brand],
    ["primary", color.primary.default],
    ["primary-hover", color.primary.hover],
    ["primary-active", color.primary.active],
    ["primary-foreground", color.primary.foreground],
    ["accent-foreground", color.accentForeground],
  ];

  for (const name of semanticColorNames) {
    const intent = color.semantic[name];
    colors.push(
      [name, intent.default],
      [`${name}-hover`, intent.hover],
      [`${name}-active`, intent.active],
      [`${name}-foreground`, intent.foreground],
    );
  }

  for (const accent of accentPalette) {
    colors.push([`accent-${accent.name}`, accent.value], [`accent-${accent.ordinal}`, accent.value]);
  }

  const themeLines = [
    "  --color-*: initial;",
    ...colors.map(([name, value]) => `  --color-${name}: ${value};`),
    `  --font-sans: ${typography.sans};`,
    `  --font-display: ${typography.display};`,
    `  --font-mono: ${typography.mono};`,
    `  --ease-draw: ${easing.draw};`,
    `  --ease-converge: ${easing.converge};`,
    `  --shadow-glow: ${effect.glow};`,
  ];

  return `/* Generated by scripts/generate-theme.ts. Do not edit directly. */\n@theme static {\n${themeLines.join("\n")}\n}\n`;
}
