import { cp, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join, relative, resolve, sep } from "node:path";
import { buildBlogArtifact, type PublishedPost } from "@th-m/blogs/publish";

const projectRoot = resolve(import.meta.dir, "..");
const blogsRoot = resolve(projectRoot, "../../libs/blogs");
const sourceRoot = resolve(blogsRoot, "dist");
const targetRoot = resolve(projectRoot, "public/_content");
const generatedRoot = resolve(projectRoot, "src/generated/blog-pages");

function assertInsideProject(root: string, candidate: string, label: string): void {
  const path = relative(root, candidate);
  if (path === ".." || path.startsWith(`..${sep}`)) {
    throw new Error(`Generated content path escapes the portfolio project: ${candidate} (${label})`);
  }
}

async function removeTypeScriptFiles(directory: string): Promise<void> {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) await removeTypeScriptFiles(path);
    else if (entry.name.endsWith(".tsx")) await rm(path);
  }
}

function pageImportName(slug: string): string {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

async function stageBlogPages(posts: PublishedPost[]): Promise<void> {
  assertInsideProject(projectRoot, generatedRoot, "generated pages");
  await rm(generatedRoot, { recursive: true, force: true });
  await mkdir(generatedRoot, { recursive: true });

  const pagePosts = posts.filter((post) => post.page === true);
  const imports: string[] = [];
  const entries: string[] = [];

  for (const post of pagePosts) {
    const pageDirectory = join(generatedRoot, post.slug);
    const sourcePage = join(sourceRoot, "posts", post.slug, "index.tsx");
    await mkdir(pageDirectory, { recursive: true });
    await cp(sourcePage, join(pageDirectory, "index.tsx"));
    const identifier = pageImportName(post.slug);
    imports.push(`import ${identifier} from "./${post.slug}";`);
    entries.push(`  "${post.slug}": ${identifier},`);
  }

  const registry = [
    "/* Generated by scripts/prepare-content.ts. Do not edit directly. */",
    'import type { ComponentType } from "react";',
    'import type { ArticlePageProps } from "../../writing/article-page";',
    "",
    ...imports,
    "",
    "export const blogPages: Record<string, ComponentType<ArticlePageProps>> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
  await writeFile(join(generatedRoot, "registry.ts"), registry);
}

assertInsideProject(projectRoot, targetRoot, "published content");

const manifest = await buildBlogArtifact(blogsRoot);
await rm(targetRoot, { recursive: true, force: true });
await mkdir(targetRoot, { recursive: true });
await cp(sourceRoot, targetRoot, { recursive: true });
await removeTypeScriptFiles(targetRoot);
await stageBlogPages(manifest.posts);

console.log(
  `Prepared ${manifest.posts.length} published article${manifest.posts.length === 1 ? "" : "s"} ` +
    `(${manifest.posts.filter((post) => post.page).length} with React pages) for the portfolio.`,
);
