import { cp, mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import type { Dirent } from "node:fs";
import { join, relative, resolve, sep } from "node:path";
import { buildBlogArtifact, type PublishedPost } from "@th-m/blogs/publish";

const projectRoot = resolve(import.meta.dir, "..");
const blogsRoot = resolve(projectRoot, "../../libs/blogs");
const sourceRoot = resolve(blogsRoot, "dist");
const targetRoot = resolve(projectRoot, "public/_content");
const generatedRoot = resolve(projectRoot, "src/generated/blog-pages");
const prepareLock = resolve(projectRoot, ".prepare-content.lock");

function assertInsideProject(root: string, candidate: string, label: string): void {
  const path = relative(root, candidate);
  if (path === ".." || path.startsWith(`..${sep}`)) {
    throw new Error(`Generated content path escapes the portfolio project: ${candidate} (${label})`);
  }
}

async function removePublicPageSources(posts: PublishedPost[]): Promise<void> {
  for (const post of posts.filter((candidate) => candidate.page === true)) {
    const publicPostDirectory = join(targetRoot, "posts", post.slug);
    let entries: Dirent[];
    try {
      entries = await readdir(publicPostDirectory, { withFileTypes: true });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
      throw error;
    }
    for (const entry of entries) {
      if (entry.isFile() && (entry.name.endsWith(".tsx") || entry.name.endsWith(".css"))) {
        await rm(join(publicPostDirectory, entry.name), { force: true });
      }
    }
  }
}

async function acquirePrepareLock(): Promise<void> {
  for (let attempt = 0; attempt < 600; attempt += 1) {
    try {
      await mkdir(prepareLock);
      return;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
      const lock = await stat(prepareLock).catch(() => undefined);
      if (lock && Date.now() - lock.mtimeMs > 60_000) {
        await rm(prepareLock, { recursive: true, force: true });
        continue;
      }
      await Bun.sleep(50);
    }
  }
  throw new Error("Timed out waiting for the portfolio content preparation lock.");
}

function pageImportName(slug: string): string {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

async function stageBlogPages(posts: PublishedPost[]): Promise<void> {
  assertInsideProject(projectRoot, generatedRoot, "generated pages");
  await rm(generatedRoot, { recursive: true, force: true });
  await mkdir(generatedRoot, { recursive: true });

  const pagePosts = posts.filter((post) => post.page === true);
  const imports: string[] = [];
  const entries: string[] = [];

  for (const post of pagePosts) {
    const pageDirectory = join(generatedRoot, post.slug);
    const sourcePageDirectory = join(sourceRoot, "posts", post.slug);
    await mkdir(pageDirectory, { recursive: true });
    const pageModules = (await readdir(sourcePageDirectory, { withFileTypes: true }))
      .filter((entry) => entry.isFile() && (entry.name.endsWith(".tsx") || entry.name.endsWith(".css")))
      .map((entry) => entry.name)
      .sort((left, right) => left.localeCompare(right, "en"));
    for (const name of pageModules) {
      await cp(join(sourcePageDirectory, name), join(pageDirectory, name));
    }
    const identifier = pageImportName(post.slug);
    imports.push(`import ${identifier} from "./${post.slug}";`);
    entries.push(`  "${post.slug}": ${identifier},`);
  }

  const registry = [
    "/* Generated by scripts/prepare-content.ts. Do not edit directly. */",
    'import type { ComponentType } from "react";',
    'import type { ArticlePageProps } from "../../writing/article-page";',
    "",
    ...imports,
    "",
    "export const blogPages: Record<string, ComponentType<ArticlePageProps>> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
  await writeFile(join(generatedRoot, "registry.ts"), registry);
}

assertInsideProject(projectRoot, targetRoot, "published content");
assertInsideProject(projectRoot, prepareLock, "preparation lock");

await acquirePrepareLock();
try {
  const manifest = await buildBlogArtifact(blogsRoot);
  await rm(targetRoot, { recursive: true, force: true });
  await mkdir(targetRoot, { recursive: true });
  await cp(sourceRoot, targetRoot, { recursive: true });
  await removePublicPageSources(manifest.posts);
  await stageBlogPages(manifest.posts);

  console.log(
    `Prepared ${manifest.posts.length} published article${manifest.posts.length === 1 ? "" : "s"} ` +
      `(${manifest.posts.filter((post) => post.page).length} with React pages) for the portfolio.`,
  );
} finally {
  await rm(prepareLock, { recursive: true, force: true });
}
