import { cp, mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import type { Dirent } from "node:fs";
import { join, relative, resolve, sep } from "node:path";
import { buildBlogArtifact, type PublishedPost } from "@th-m/blogs/publish";

const projectRoot = resolve(import.meta.dir, "..");
const blogsRoot = resolve(projectRoot, "../../libs/blogs");
const sourceRoot = resolve(blogsRoot, "dist");
const targetRoot = resolve(projectRoot, "public/_content");
const generatedRoot = resolve(projectRoot, "src/generated/blog-pages");
const prepareLock = resolve(projectRoot, ".prepare-content.lock");

function assertInsideProject(root: string, candidate: string, label: string): void {
  const path = relative(root, candidate);
  if (path === ".." || path.startsWith(`..${sep}`)) {
    throw new Error(`Generated content path escapes the portfolio project: ${candidate} (${label})`);
  }
}

async function removePublicCompileSources(posts: PublishedPost[]): Promise<void> {
  for (const post of posts) {
    const publicPostDirectory = join(targetRoot, "posts", post.slug);
    let entries: Dirent[];
    try {
      entries = await readdir(publicPostDirectory, { withFileTypes: true });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
      throw error;
    }
    for (const entry of entries) {
      if (entry.isFile() && (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx") || entry.name.endsWith(".css"))) {
        await rm(join(publicPostDirectory, entry.name), { force: true });
      }
    }
  }
}

async function acquirePrepareLock(): Promise<void> {
  for (let attempt = 0; attempt < 600; attempt += 1) {
    try {
      await mkdir(prepareLock);
      return;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
      const lock = await stat(prepareLock).catch(() => undefined);
      if (lock && Date.now() - lock.mtimeMs > 60_000) {
        await rm(prepareLock, { recursive: true, force: true });
        continue;
      }
      await Bun.sleep(50);
    }
  }
  throw new Error("Timed out waiting for the portfolio content preparation lock.");
}

function pageImportName(slug: string): string {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

async function stageBlogArticles(posts: PublishedPost[]): Promise<void> {
  assertInsideProject(projectRoot, generatedRoot, "generated pages");
  await rm(generatedRoot, { recursive: true, force: true });
  await mkdir(generatedRoot, { recursive: true });

  const imports: string[] = [];
  const entries: string[] = [];

  for (const post of posts) {
    const pageDirectory = join(generatedRoot, post.slug);
    const sourcePageDirectory = join(sourceRoot, "posts", post.slug);
    await mkdir(pageDirectory, { recursive: true });
    const pageModules = (await readdir(sourcePageDirectory, { withFileTypes: true }))
      .filter((entry) => entry.isFile() && (
        entry.name.endsWith(".mdx") || entry.name.endsWith(".ts") || entry.name.endsWith(".tsx") || entry.name.endsWith(".css")
      ))
      .map((entry) => entry.name)
      .sort((left, right) => left.localeCompare(right, "en"));
    for (const name of pageModules) {
      await cp(join(sourcePageDirectory, name), join(pageDirectory, name));
    }
    const identifier = pageImportName(post.slug);
    const componentModule = pageModules.includes("article-components.tsx");
    imports.push(`import ${identifier}Content from "./${post.slug}/article.mdx";`);
    imports.push(`import ${identifier}Assets from "./${post.slug}/article-assets";`);
    if (componentModule) imports.push(`import ${identifier}Components from "./${post.slug}/article-components";`);
    for (const cssModule of pageModules.filter((name) => name.endsWith(".css"))) {
      imports.push(`import "./${post.slug}/${cssModule}";`);
    }
    entries.push(
      `  "${post.slug}": { Content: ${identifier}Content, assets: ${identifier}Assets${
        componentModule ? `, createComponents: ${identifier}Components` : ""
      } },`,
    );
  }

  const registry = [
    "/* Generated by scripts/prepare-content.ts. Do not edit directly. */",
    'import type { ComponentType } from "react";',
    'import type { MDXProps } from "mdx/types";',
    'import type { ArticleAssetRegistry, ArticleRenderContext } from "@th-m/blogs/mdx";',
    "",
    ...imports,
    "",
    "export interface GeneratedBlogArticle {",
    "  Content: ComponentType<MDXProps>;",
    "  assets: ArticleAssetRegistry;",
    "  createComponents?: (context: ArticleRenderContext) => Record<string, ComponentType<never>>;",
    "}",
    "",
    "export const blogArticles: Record<string, GeneratedBlogArticle> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
  await writeFile(join(generatedRoot, "registry.ts"), registry);
}

assertInsideProject(projectRoot, targetRoot, "published content");
assertInsideProject(projectRoot, prepareLock, "preparation lock");

await acquirePrepareLock();
try {
  const manifest = await buildBlogArtifact(blogsRoot);
  await rm(targetRoot, { recursive: true, force: true });
  await mkdir(targetRoot, { recursive: true });
  await cp(sourceRoot, targetRoot, { recursive: true });
  await removePublicCompileSources(manifest.posts);
  await stageBlogArticles(manifest.posts);

  console.log(
    `Prepared ${manifest.posts.length} published article${manifest.posts.length === 1 ? "" : "s"} ` +
      `(all compiled from MDX) for the portfolio.`,
  );
} finally {
  await rm(prepareLock, { recursive: true, force: true });
}
