/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as EmbeddingSpaceRouteImport } from './routes/embedding-space'
import { Route as LawsRouteImport } from './routes/laws'
import { Route as LlmVisualizationRouteImport } from './routes/llm-visualization'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RelationshipGraphRouteImport } from './routes/relationship-graph'
import { Route as SpaShellRouteImport } from './routes/spa-shell'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddingSpaceRoute = EmbeddingSpaceRouteImport.update({
  id: '/embedding-space',
  path: '/embedding-space',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsRoute = LawsRouteImport.update({
  id: '/laws',
  path: '/laws',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmVisualizationRoute = LlmVisualizationRouteImport.update({
  id: '/llm-visualization',
  path: '/llm-visualization',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const RelationshipGraphRoute = RelationshipGraphRouteImport.update({
  id: '/relationship-graph',
  path: '/relationship-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaShellRoute = SpaShellRouteImport.update({
  id: '/spa-shell',
  path: '/spa-shell',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/design-system': typeof DesignSystemRoute
  '/embedding-space': typeof EmbeddingSpaceRoute
  '/laws': typeof LawsRoute
  '/llm-visualization': typeof LlmVisualizationRoute
  '/login': typeof LoginRoute
  '/relationship-graph': typeof RelationshipGraphRoute
  '/spa-shell': typeof SpaShellRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/design-system': typeof DesignSystemRoute
  '/embedding-space': typeof EmbeddingSpaceRoute
  '/laws': typeof LawsRoute
  '/llm-visualization': typeof LlmVisualizationRoute
  '/login': typeof LoginRoute
  '/relationship-graph': typeof RelationshipGraphRoute
  '/spa-shell': typeof SpaShellRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/design-system': typeof DesignSystemRoute
  '/embedding-space': typeof EmbeddingSpaceRoute
  '/laws': typeof LawsRoute
  '/llm-visualization': typeof LlmVisualizationRoute
  '/login': typeof LoginRoute
  '/relationship-graph': typeof RelationshipGraphRoute
  '/spa-shell': typeof SpaShellRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/design-system'
    | '/embedding-space'
    | '/laws'
    | '/llm-visualization'
    | '/login'
    | '/relationship-graph'
    | '/spa-shell'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/design-system'
    | '/embedding-space'
    | '/laws'
    | '/llm-visualization'
    | '/login'
    | '/relationship-graph'
    | '/spa-shell'
    | '/writing/$slug'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/design-system'
    | '/embedding-space'
    | '/laws'
    | '/llm-visualization'
    | '/login'
    | '/relationship-graph'
    | '/spa-shell'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EmbeddingSpaceRoute: typeof EmbeddingSpaceRoute
  LawsRoute: typeof LawsRoute
  LlmVisualizationRoute: typeof LlmVisualizationRoute
  LoginRoute: typeof LoginRoute
  RelationshipGraphRoute: typeof RelationshipGraphRoute
  SpaShellRoute: typeof SpaShellRoute
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedding-space': {
      id: '/embedding-space'
      path: '/embedding-space'
      fullPath: '/embedding-space'
      preLoaderRoute: typeof EmbeddingSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws': {
      id: '/laws'
      path: '/laws'
      fullPath: '/laws'
      preLoaderRoute: typeof LawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-visualization': {
      id: '/llm-visualization'
      path: '/llm-visualization'
      fullPath: '/llm-visualization'
      preLoaderRoute: typeof LlmVisualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship-graph': {
      id: '/relationship-graph'
      path: '/relationship-graph'
      fullPath: '/relationship-graph'
      preLoaderRoute: typeof RelationshipGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa-shell': {
      id: '/spa-shell'
      path: '/spa-shell'
      fullPath: '/spa-shell'
      preLoaderRoute: typeof SpaShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  DesignSystemRoute: DesignSystemRoute,
  EmbeddingSpaceRoute: EmbeddingSpaceRoute,
  LawsRoute: LawsRoute,
  LlmVisualizationRoute: LlmVisualizationRoute,
  LoginRoute: LoginRoute,
  RelationshipGraphRoute: RelationshipGraphRoute,
  SpaShellRoute: SpaShellRoute,
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
