// Generated by scripts/generate-curated-atlases.ts — do not edit by hand.
// Deterministic TypeScript compiler analysis of curated snippets, committed so
// the static portfolio can render set atlases without a compiler in the browser.
import type { AnalyzeResult } from "@th-m/knowledge-model";

export interface CuratedSetAtlasEntry {
  id: string;
  label: string;
  description: string;
  analysis: AnalyzeResult;
}

export const curatedSetAtlasAnalyses: CuratedSetAtlasEntry[] = [
  {
    "id": "traffic-light",
    "label": "Traffic light",
    "description": "Union and intersection types as overlapping sets of literal values.",
    "analysis": {
      "revision": 1,
      "compilerVersion": "7.0.2",
      "sourceText": "type CanCross = \"green\" | \"orange\";\ntype ShouldStop = \"orange\" | \"red\";\ntype TrafficLight = CanCross | ShouldStop;\n\ntype WithName = { name: string };\ntype WithAge = { age: number };\ntype User = WithName & WithAge;\n\ntype Universe = unknown;\ntype Impossible = string & number;\ntype EscapeHatch = any;\ntype Collection<T> = T[];\n",
      "sourceFilePath": "traffic-light.ts",
      "diagnostics": [],
      "symbols": [
        {
          "id": "type-1ruqzyd",
          "name": "CanCross",
          "kind": "alias",
          "display": "\"green\" | \"orange\"",
          "status": "region",
          "typeFlags": 134217728,
          "sourceSpan": {
            "start": 0,
            "end": 35,
            "line": 1,
            "column": 1
          },
          "atomIds": [
            "atom-10kya4b",
            "atom-n7q5s"
          ]
        },
        {
          "id": "type-1tb7i94",
          "name": "ShouldStop",
          "kind": "alias",
          "display": "\"orange\" | \"red\"",
          "status": "region",
          "typeFlags": 134217728,
          "sourceSpan": {
            "start": 36,
            "end": 71,
            "line": 2,
            "column": 1
          },
          "atomIds": [
            "atom-n7q5s",
            "atom-1fx51ef"
          ]
        },
        {
          "id": "type-lwypgk",
          "name": "TrafficLight",
          "kind": "alias",
          "display": "CanCross | ShouldStop",
          "status": "region",
          "typeFlags": 134217728,
          "sourceSpan": {
            "start": 72,
            "end": 114,
            "line": 3,
            "column": 1
          },
          "atomIds": [
            "atom-10kya4b",
            "atom-n7q5s",
            "atom-1fx51ef"
          ]
        },
        {
          "id": "type-1ovxv3k",
          "name": "WithName",
          "kind": "alias",
          "display": "{ name: string }",
          "status": "region",
          "typeFlags": 1048576,
          "sourceSpan": {
            "start": 116,
            "end": 149,
            "line": 5,
            "column": 1
          },
          "atomIds": []
        },
        {
          "id": "type-66kje",
          "name": "WithAge",
          "kind": "alias",
          "display": "{ age: number }",
          "status": "region",
          "typeFlags": 1048576,
          "sourceSpan": {
            "start": 150,
            "end": 181,
            "line": 6,
            "column": 1
          },
          "atomIds": []
        },
        {
          "id": "type-1d3pihs",
          "name": "User",
          "kind": "alias",
          "display": "WithName & WithAge",
          "status": "region",
          "typeFlags": 268435456,
          "sourceSpan": {
            "start": 182,
            "end": 213,
            "line": 7,
            "column": 1
          },
          "atomIds": []
        },
        {
          "id": "type-8ujgxg",
          "name": "Universe",
          "kind": "alias",
          "display": "unknown",
          "status": "universe",
          "typeFlags": 2,
          "sourceSpan": {
            "start": 215,
            "end": 239,
            "line": 9,
            "column": 1
          },
          "detail": "The universe set: every TypeScript value is assignable to `unknown`.",
          "atomIds": []
        },
        {
          "id": "type-14vownq",
          "name": "Impossible",
          "kind": "alias",
          "display": "string & number",
          "status": "empty",
          "typeFlags": 262144,
          "sourceSpan": {
            "start": 240,
            "end": 274,
            "line": 10,
            "column": 1
          },
          "detail": "The empty set: `never` has no values.",
          "atomIds": []
        },
        {
          "id": "type-fe46gq",
          "name": "EscapeHatch",
          "kind": "alias",
          "display": "any",
          "status": "exception",
          "typeFlags": 1,
          "sourceSpan": {
            "start": 275,
            "end": 298,
            "line": 11,
            "column": 1
          },
          "detail": "`any` is intentionally shown outside set semantics.",
          "atomIds": []
        },
        {
          "id": "type-1d5ychn",
          "name": "Collection",
          "kind": "alias",
          "display": "T[]",
          "status": "template",
          "typeFlags": 1048576,
          "sourceSpan": {
            "start": 299,
            "end": 324,
            "line": 12,
            "column": 1
          },
          "detail": "Generic template with 1 type parameter; instantiate it to visualize a set.",
          "atomIds": []
        }
      ],
      "relations": [
        {
          "sourceId": "type-1ruqzyd",
          "targetId": "type-1tb7i94",
          "kind": "overlap",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1ruqzyd",
          "targetId": "type-lwypgk",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1ruqzyd",
          "targetId": "type-1ovxv3k",
          "kind": "overlap",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-1ruqzyd",
          "targetId": "type-66kje",
          "kind": "overlap",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-1ruqzyd",
          "targetId": "type-1d3pihs",
          "kind": "overlap",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1ruqzyd",
          "targetId": "type-8ujgxg",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-1ruqzyd",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1ruqzyd",
          "targetId": "type-fe46gq",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-1ruqzyd",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-1tb7i94",
          "targetId": "type-lwypgk",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1tb7i94",
          "targetId": "type-1ovxv3k",
          "kind": "overlap",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-1tb7i94",
          "targetId": "type-66kje",
          "kind": "overlap",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-1tb7i94",
          "targetId": "type-1d3pihs",
          "kind": "overlap",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1tb7i94",
          "targetId": "type-8ujgxg",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-1tb7i94",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1tb7i94",
          "targetId": "type-fe46gq",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-1tb7i94",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-lwypgk",
          "targetId": "type-1ovxv3k",
          "kind": "overlap",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-lwypgk",
          "targetId": "type-66kje",
          "kind": "overlap",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-lwypgk",
          "targetId": "type-1d3pihs",
          "kind": "overlap",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-lwypgk",
          "targetId": "type-8ujgxg",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-lwypgk",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-lwypgk",
          "targetId": "type-fe46gq",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-lwypgk",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-1ovxv3k",
          "targetId": "type-66kje",
          "kind": "overlap",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-1d3pihs",
          "targetId": "type-1ovxv3k",
          "kind": "proper-subset",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-1ovxv3k",
          "targetId": "type-8ujgxg",
          "kind": "proper-subset",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-1ovxv3k",
          "kind": "proper-subset",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-1ovxv3k",
          "targetId": "type-fe46gq",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-1ovxv3k",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-1d3pihs",
          "targetId": "type-66kje",
          "kind": "proper-subset",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-66kje",
          "targetId": "type-8ujgxg",
          "kind": "proper-subset",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-66kje",
          "kind": "proper-subset",
          "confidence": "derived",
          "reason": "Structural object sets are open; this relation is derived from compiler assignability."
        },
        {
          "sourceId": "type-66kje",
          "targetId": "type-fe46gq",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-66kje",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-1d3pihs",
          "targetId": "type-8ujgxg",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-1d3pihs",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1d3pihs",
          "targetId": "type-fe46gq",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-1d3pihs",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-8ujgxg",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-8ujgxg",
          "targetId": "type-fe46gq",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-8ujgxg",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-fe46gq",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-14vownq",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-fe46gq",
          "targetId": "type-1d5ychn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        }
      ],
      "atoms": [
        {
          "id": "atom-10kya4b",
          "label": "\"green\"",
          "kind": "literal",
          "ownerIds": [
            "type-1ruqzyd",
            "type-lwypgk"
          ]
        },
        {
          "id": "atom-n7q5s",
          "label": "\"orange\"",
          "kind": "literal",
          "ownerIds": [
            "type-1ruqzyd",
            "type-1tb7i94",
            "type-lwypgk"
          ]
        },
        {
          "id": "atom-1fx51ef",
          "label": "\"red\"",
          "kind": "literal",
          "ownerIds": [
            "type-1tb7i94",
            "type-lwypgk"
          ]
        }
      ]
    }
  },
  {
    "id": "typescript-sets",
    "label": "TypeScript is set theory",
    "description": "The seed workbench: unions, the universe, the empty set, and escape hatches.",
    "analysis": {
      "revision": 1,
      "compilerVersion": "7.0.2",
      "sourceText": "// TypeScript types describe sets of possible values.\n// Stop and Caution overlap at \"amber\"; Signal contains both.\ntype Stop = \"red\" | \"amber\";\ntype Caution = \"amber\" | \"yellow\";\ntype Go = \"green\";\ntype Signal = Stop | Caution | Go;\n\n// The universe, the empty set, and TypeScript's set-breaking escape hatch.\ntype Everything = unknown;\ntype Nothing = never;\ntype EscapeHatch = any;\n\n// An uninstantiated generic is a reusable set template.\ntype Box<Value> = {\n  value: Value;\n};\n",
      "sourceFilePath": "typescript-sets.ts",
      "diagnostics": [],
      "symbols": [
        {
          "id": "type-1j2vkv8",
          "name": "Stop",
          "kind": "alias",
          "display": "\"red\" | \"amber\"",
          "status": "region",
          "typeFlags": 134217728,
          "sourceSpan": {
            "start": 116,
            "end": 144,
            "line": 3,
            "column": 1
          },
          "atomIds": [
            "atom-17w73fj",
            "atom-1fx51ef"
          ]
        },
        {
          "id": "type-19culf1",
          "name": "Caution",
          "kind": "alias",
          "display": "\"amber\" | \"yellow\"",
          "status": "region",
          "typeFlags": 134217728,
          "sourceSpan": {
            "start": 145,
            "end": 179,
            "line": 4,
            "column": 1
          },
          "atomIds": [
            "atom-17w73fj",
            "atom-igppqe"
          ]
        },
        {
          "id": "type-1jc13dm",
          "name": "Go",
          "kind": "alias",
          "display": "\"green\"",
          "status": "region",
          "typeFlags": 1024,
          "sourceSpan": {
            "start": 180,
            "end": 198,
            "line": 5,
            "column": 1
          },
          "atomIds": [
            "atom-10kya4b"
          ]
        },
        {
          "id": "type-13b6c7s",
          "name": "Signal",
          "kind": "alias",
          "display": "Stop | Caution | Go",
          "status": "region",
          "typeFlags": 134217728,
          "sourceSpan": {
            "start": 199,
            "end": 233,
            "line": 6,
            "column": 1
          },
          "atomIds": [
            "atom-17w73fj",
            "atom-10kya4b",
            "atom-1fx51ef",
            "atom-igppqe"
          ]
        },
        {
          "id": "type-1as69dp",
          "name": "Everything",
          "kind": "alias",
          "display": "unknown",
          "status": "universe",
          "typeFlags": 2,
          "sourceSpan": {
            "start": 311,
            "end": 337,
            "line": 9,
            "column": 1
          },
          "detail": "The universe set: every TypeScript value is assignable to `unknown`.",
          "atomIds": []
        },
        {
          "id": "type-1ulvx15",
          "name": "Nothing",
          "kind": "alias",
          "display": "never",
          "status": "empty",
          "typeFlags": 262144,
          "sourceSpan": {
            "start": 338,
            "end": 359,
            "line": 10,
            "column": 1
          },
          "detail": "The empty set: `never` has no values.",
          "atomIds": []
        },
        {
          "id": "type-31e5xn",
          "name": "EscapeHatch",
          "kind": "alias",
          "display": "any",
          "status": "exception",
          "typeFlags": 1,
          "sourceSpan": {
            "start": 360,
            "end": 383,
            "line": 11,
            "column": 1
          },
          "detail": "`any` is intentionally shown outside set semantics.",
          "atomIds": []
        },
        {
          "id": "type-rei4hx",
          "name": "Box",
          "kind": "alias",
          "display": "{\n  value: Value;\n}",
          "status": "template",
          "typeFlags": 1048576,
          "sourceSpan": {
            "start": 442,
            "end": 480,
            "line": 14,
            "column": 1
          },
          "detail": "Generic template with 1 type parameter; instantiate it to visualize a set.",
          "atomIds": []
        }
      ],
      "relations": [
        {
          "sourceId": "type-1j2vkv8",
          "targetId": "type-19culf1",
          "kind": "overlap",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1j2vkv8",
          "targetId": "type-1jc13dm",
          "kind": "disjoint",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1j2vkv8",
          "targetId": "type-13b6c7s",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1j2vkv8",
          "targetId": "type-1as69dp",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1ulvx15",
          "targetId": "type-1j2vkv8",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1j2vkv8",
          "targetId": "type-31e5xn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-1j2vkv8",
          "targetId": "type-rei4hx",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-19culf1",
          "targetId": "type-1jc13dm",
          "kind": "disjoint",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-19culf1",
          "targetId": "type-13b6c7s",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-19culf1",
          "targetId": "type-1as69dp",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1ulvx15",
          "targetId": "type-19culf1",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-19culf1",
          "targetId": "type-31e5xn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-19culf1",
          "targetId": "type-rei4hx",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-1jc13dm",
          "targetId": "type-13b6c7s",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1jc13dm",
          "targetId": "type-1as69dp",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1ulvx15",
          "targetId": "type-1jc13dm",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1jc13dm",
          "targetId": "type-31e5xn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-1jc13dm",
          "targetId": "type-rei4hx",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-13b6c7s",
          "targetId": "type-1as69dp",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1ulvx15",
          "targetId": "type-13b6c7s",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-13b6c7s",
          "targetId": "type-31e5xn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-13b6c7s",
          "targetId": "type-rei4hx",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-1ulvx15",
          "targetId": "type-1as69dp",
          "kind": "proper-subset",
          "confidence": "compiler-proven"
        },
        {
          "sourceId": "type-1as69dp",
          "targetId": "type-31e5xn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-1as69dp",
          "targetId": "type-rei4hx",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-1ulvx15",
          "targetId": "type-31e5xn",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "`any` does not behave as a mathematical set, so this relation is intentionally indeterminate."
        },
        {
          "sourceId": "type-1ulvx15",
          "targetId": "type-rei4hx",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        },
        {
          "sourceId": "type-31e5xn",
          "targetId": "type-rei4hx",
          "kind": "indeterminate",
          "confidence": "approximate",
          "reason": "Instantiate generic templates before comparing their sets."
        }
      ],
      "atoms": [
        {
          "id": "atom-17w73fj",
          "label": "\"amber\"",
          "kind": "literal",
          "ownerIds": [
            "type-13b6c7s",
            "type-19culf1",
            "type-1j2vkv8"
          ]
        },
        {
          "id": "atom-1fx51ef",
          "label": "\"red\"",
          "kind": "literal",
          "ownerIds": [
            "type-13b6c7s",
            "type-1j2vkv8"
          ]
        },
        {
          "id": "atom-igppqe",
          "label": "\"yellow\"",
          "kind": "literal",
          "ownerIds": [
            "type-13b6c7s",
            "type-19culf1"
          ]
        },
        {
          "id": "atom-10kya4b",
          "label": "\"green\"",
          "kind": "literal",
          "ownerIds": [
            "type-13b6c7s",
            "type-1jc13dm"
          ]
        }
      ]
    }
  },
  {
    "id": "shared-members",
    "label": "Shared members",
    "description": "Two unions that overlap on one literal — the simplest overlapping sets.",
    "analysis": {
      "revision": 1,
      "compilerVersion": "7.0.2",
      "sourceText": "type A = \"shared\" | \"only-a\";\ntype B = \"shared\" | \"only-b\";\n",
      "sourceFilePath": "shared-members.ts",
      "diagnostics": [],
      "symbols": [
        {
          "id": "type-6jl0z7",
          "name": "A",
          "kind": "alias",
          "display": "\"shared\" | \"only-a\"",
          "status": "region",
          "typeFlags": 134217728,
          "sourceSpan": {
            "start": 0,
            "end": 29,
            "line": 1,
            "column": 1
          },
          "atomIds": [
            "atom-11h7x96",
            "atom-1vhpaqd"
          ]
        },
        {
          "id": "type-6tkmo6",
          "name": "B",
          "kind": "alias",
          "display": "\"shared\" | \"only-b\"",
          "status": "region",
          "typeFlags": 134217728,
          "sourceSpan": {
            "start": 30,
            "end": 59,
            "line": 2,
            "column": 1
          },
          "atomIds": [
            "atom-1x482tx",
            "atom-1vhpaqd"
          ]
        }
      ],
      "relations": [
        {
          "sourceId": "type-6jl0z7",
          "targetId": "type-6tkmo6",
          "kind": "overlap",
          "confidence": "compiler-proven"
        }
      ],
      "atoms": [
        {
          "id": "atom-11h7x96",
          "label": "\"only-a\"",
          "kind": "literal",
          "ownerIds": [
            "type-6jl0z7"
          ]
        },
        {
          "id": "atom-1vhpaqd",
          "label": "\"shared\"",
          "kind": "literal",
          "ownerIds": [
            "type-6jl0z7",
            "type-6tkmo6"
          ]
        },
        {
          "id": "atom-1x482tx",
          "label": "\"only-b\"",
          "kind": "literal",
          "ownerIds": [
            "type-6tkmo6"
          ]
        }
      ]
    }
  }
];
