// Generated by scripts/fetch-laws.ts from lawsofux.com and timsommer.be. Do not edit directly.
import type { Law } from "../types";

export const aestheticUsabilityEffect: Law = {
  slug: "aesthetic-usability-effect",
  title: "Aesthetic-Usability Effect",
  definition: "Users often perceive aesthetically pleasing design as design that’s more usable.",
  category: "theory",
  color: "#506485",
  labels: ["design","ui","psychology"],
  takeaways: ["An aesthetically pleasing design creates a positive response in people’s brains and leads them to believe the design actually works better.","People are more tolerant of minor usability issues when the design of a product or service is aesthetically pleasing.","Visually pleasing design can mask usability problems and prevent issues from being discovered during usability testing."],
  copy: ["The aesthetic-usability effect was first studied in the field of human–computer interaction in 1995. Researchers Masaaki Kurosu and Kaori Kashimura from the Hitachi Design Center tested 26 variations of an ATM UI, asking the 252 study participants to rate each design on ease of use, as well as aesthetic appeal. They found a stronger correlation between the participants’ ratings of aesthetic appeal and perceived ease of use than the correlation between their ratings of aesthetic appeal and actual ease of use. Kurosu and Kashimura concluded that users are strongly influenced by the aesthetics of any given interface, even when they try to evaluate the underlying functionality of the system."],
  source: "https://www.nngroup.com/articles/aesthetic-usability-effect/",
  furtherReading: [{"title":"The Aesthetic-Usability Effect","url":"https://www.nngroup.com/articles/aesthetic-usability-effect/","source":"Kate Moran | Nielsen Norman Group"},{"title":"The Aesthetic Usability Effect and Prioritizing Appearance vs. Functionality","url":"https://www.nngroup.com/videos/aesthetic-usability-effect/","source":"Kathryn Whitenton | Nielsen Norman Group"},{"title":"Aesthetic Usability Effect","url":"https://en.wikipedia.org/wiki/Aesthetic_usability_effect","source":"Wikipedia"},{"title":"The Aesthetic-Usability Effect: Why Beautiful-Looking Products are Preferred Over Usable-But-Not-Beautiful Ones","url":"https://medium.com/coffee-and-junk/design-psychology-aesthetic-usability-effect-494ed0f22571","source":"Abhishek Chakraborty | Medium"},{"title":"A Neuropsychological Theory of Positive Affect and Its Influence on Cognition","url":"https://www.researchgate.net/publication/12831914_A_Neuropsychological_Theory_of_Positive_Affect_and_Its_Influence_on_Cognition","source":"F. Gregory Ashby"}],
  graphic: "<svg viewbox=\"0 0 566 566\" xmlns=\"http://www.w3.org/2000/svg\"><circle style=\"--animation-order: 1\" fill-opacity=\".15\" fill=\"#000\" cx=\"282.882\" cy=\"282.882\" r=\"282.882\"/><path style=\"--animation-order: 2\" fill-opacity=\".15\" fill=\"#000\" d=\"M82.937 82.897h399.886v399.967H82.937z\"/><path style=\"--animation-order: 3\" fill=\"#f4f1d0\" d=\"M282.88 82.897l199.943 399.966H82.937z\"/></svg>",
  sources: ["https://lawsofux.com/aesthetic-usability-effect/"],
  related: ["choice-overload"],
};
