// Generated by scripts/fetch-laws.ts from lawsofux.com and timsommer.be. Do not edit directly.
import type { Law } from "../types";

export const dohertyThreshold: Law = {
  slug: "doherty-threshold",
  title: "Doherty Threshold",
  definition: "Productivity soars when a computer and its users interact at a pace (<400ms) that ensures that neither has to wait on the other.",
  category: "theory",
  color: "#a6307f",
  labels: ["ui","cs","psychology"],
  takeaways: ["Provide system feedback within 400 ms in order to keep users’ attention and increase productivity.","Use perceived performance to improve response time and reduce the perception of waiting.","Animation is one way to visually engage people while loading or processing is happening in the background.","Progress bars help make wait times tolerable, regardless of their accuracy.","Purposefully adding a delay to a process can actually increase its perceived value and instill a sense of trust, even when the process itself actually takes much less time."],
  copy: ["In 1982 Walter J. Doherty and Ahrvind J. Thadani published, in the IBM Systems Journal, a research paper that set the requirement for computer response time to be 400 milliseconds, not 2,000 (2 seconds) which had been the previous standard. When a human being’s command was executed and returned an answer in under 400 milliseconds, it was deemed to exceed the Doherty threshold, and use of such applications were deemed to be “addicting” to users."],
  furtherReading: [{"title":"The Economic Value of Rapid Response Time","url":"https://jlelliotton.blogspot.ca/p/the-economic-value-of-rapid-response.html","source":"Jim Elliott"},{"title":"This 70s UX gem still applies today","url":"https://medium.com/@Gugel/the-doherty-threshold-5471ca990de6","source":"Michael Gugel | Medium"},{"title":"The Economic Value of Rapid Response Time","url":"https://daverupert.com/2015/06/doherty-threshold/","source":"Dave Rupert"},{"title":"The importance of percent-done progress indicators for computer-human interfaces","url":"https://www.researchgate.net/publication/234791131_The_importance_of_percent-done_progress_indicators_for_computer-human_interfaces","source":"Brad A. Myers"},{"title":"Response time in man-computer conversational transactions","url":"http://yusufarslan.net/sites/yusufarslan.net/files/upload/content/Miller1968.pdf","source":"Robert B. Miller"}],
  graphic: "<svg viewbox=\"0 0 566 566\" xmlns=\"http://www.w3.org/2000/svg\"><circle style=\"--animation-order: 1\" fill-opacity=\".15\" fill=\"#000\" cx=\"282.882\" cy=\"282.882\" r=\"282.882\"/><circle style=\"--animation-order: 2\" fill-opacity=\".15\" fill=\"#000\" cx=\"282.861\" cy=\"282.861\" r=\"207.861\"/><circle style=\"--animation-order: 3\" fill-opacity=\".15\" fill=\"#000\" cx=\"283.212\" cy=\"283.212\" r=\"134.212\"/><circle style=\"--animation-order: 4\" fill=\"#f4f1d0\" cx=\"283.213\" cy=\"283.213\" r=\"60.213\"/></svg>",
  sources: ["https://lawsofux.com/doherty-threshold/"],
  related: ["choice-overload"],
};
