// Generated by scripts/fetch-laws.ts from lawsofux.com and timsommer.be. Do not edit directly.
import type { Law } from "../types";

export const fittssLaw: Law = {
  slug: "fittss-law",
  title: "Fitts’s Law",
  definition: "The time to acquire a target is a function of the distance to and size of the target.",
  category: "theory",
  color: "#5d883a",
  labels: ["ui","design","cs"],
  takeaways: ["Touch targets should be large enough for users to accurately select them.","Touch targets should have ample spacing between them.","Touch targets should be placed in areas of an interface that allow them to be easily acquired."],
  copy: ["In 1954, psychologist Paul Fitts, examining the human motor system, showed that the time required to move to a target depends on the distance to it, yet relates inversely to its size. By his law, fast movements and small targets result in greater error rates, due to the speed-accuracy trade-off. Although multiple variants of Fitts’ law exist, all encompass this idea. Fitts’ law is widely applied in user experience (UX) and user interface (UI) design. For example, this law influenced the convention of making interactive buttons large (especially on finger-operated mobile devices)—smaller buttons are more difficult (and time-consuming) to click. Likewise, the distance between a user’s task/attention area and the task-related button should be kept as short as possible."],
  source: "https://www.interaction-design.org/literature/topics/fitts-law",
  furtherReading: [{"title":"Fitts's Law and Its Applications in UX","url":"https://www.nngroup.com/articles/fitts-law/","source":"Nielsen Norman Group"},{"title":"Fitts’ Law In The Touch Era","url":"https://www.smashingmagazine.com/2022/02/fitts-law-touch-era/","source":"Smashing Magazine"},{"title":"Fitts’s Law: The Importance of Size and Distance in UI Design","url":"https://www.interaction-design.org/literature/article/fitts-s-law-the-importance-of-size-and-distance-in-ui-design","source":"Interaction Design Foundation"},{"title":"Fitts’s Law on Wikipedia","url":"https://en.wikipedia.org/wiki/Fitts%27s_law","source":"Wikipedia"},{"title":"Design for Fingers, Touch, and People, Part 1","url":"https://www.uxmatters.com/mt/archives/2017/03/design-for-fingers-touch-and-people-part-1.php","source":"Steven Hoober | UX Matters"},{"title":"The information capacity of the human motor system in controlling the amplitude of movement","url":"https://pdfs.semanticscholar.org/634c/9fde5f1c411e4487658ac738dcf18d98ea8d.pdf","source":"Semantic Scholar"}],
  graphic: "<svg viewBox=\"0 0 566 566\" xmlns=\"http://www.w3.org/2000/svg\"><g stroke=\"#f4f1d0\" stroke-width=\"30\" fill=\"none\" fill-rule=\"evenodd\"><circle style=\"--animation-order: 1\" cx=\"282.882\" cy=\"282.882\" r=\"267.882\"/><circle style=\"--animation-order: 2\" cx=\"282.861\" cy=\"282.861\" r=\"192.861\"/><circle style=\"--animation-order: 3\" cx=\"283.212\" cy=\"283.212\" r=\"119.212\"/><circle style=\"--animation-order: 4\" cx=\"283.213\" cy=\"283.213\" r=\"45.213\"/></g></svg>",
  sources: ["https://lawsofux.com/fittss-law/"],
  related: ["choice-overload"],
};
