// Generated by scripts/fetch-laws.ts from lawsofux.com and timsommer.be. Do not edit directly.
import type { Law } from "../types";

export const hofstadtersLaw: Law = {
  slug: "hofstadters-law",
  title: "Hofstadter's Law",
  definition: "It always takes longer than you expect, even when you take into account Hofstadter's Law.",
  category: "theory",
  color: "#7a8aff",
  labels: ["management","software-engineering"],
  copy: ["The Hofstadter's law was written by Douglas Hofstadter and named after him.","This law is -off course- not to be confused with Leonard Hofstadter from the Big Bang theory. Even though his quotation will make sense to some you.","The rule states:","The \"law\" is a statement regarding the difficulty of accurately estimating the time it will take to complete tasks of substantial complexity. The recursive nature of the law is a reflection of the widely experienced difficulty of estimating complex tasks despite all best efforts, including knowing that the task is complex.","That's why you must always have a buffer before you give any sort of estimation. If you want to know more on how to provide better estimations, read my post on the subject: Estimation Wizardry."],
  sources: ["https://www.timsommer.be/famous-laws-of-software-development/"],
  related: [],
};
