// Generated by scripts/fetch-laws.ts from lawsofux.com and timsommer.be. Do not edit directly.
import type { Law } from "../types";

export const jakobsLaw: Law = {
  slug: "jakobs-law",
  title: "Jakob’s Law",
  definition: "Users spend most of their time on other sites. This means that users prefer your site to work the same way as all the other sites they already know.",
  category: "theory",
  color: "#cfbb28",
  labels: ["ui","design"],
  takeaways: ["Users will transfer expectations they have built around one familiar product to another that appears similar.","By leveraging existing mental models, we can create superior user experiences in which the users can focus on their tasks rather than on learning new models.","When making changes, minimize discord by empowering users to continue using a familiar version for a limited time."],
  copy: ["Jakob’s Law was coined by Jakob Nielsen, a User Advocate and principal of the Nielsen Norman Group which he co-founded with Dr. Donald A. Norman (former VP of research at Apple Computer). Dr. Nielsen established the ‘discount usability engineering’ movement for fast and cheap improvements of user interfaces and has invented several usability methods, including heuristic evaluation."],
  source: "https://www.nngroup.com/people/jakob-nielsen/",
  furtherReading: [{"title":"Jakob’s Law of Internet User Experience","url":"https://www.nngroup.com/videos/jakobs-law-internet-ux/","source":"Nielsen Norman Group"},{"title":"The Power Law of Learning: Consistency vs. Innovation in User Interfaces","url":"https://www.nngroup.com/articles/power-law-learning/","source":"Nielsen Norman Group"},{"title":"Familiar vs Novel","url":"https://lawsofux.com/articles/2024/familiar-vs-novel/","source":"Jon Yablonski | Laws of UX"},{"title":"Top 10 Mistakes in Web Design","url":"https://www.nngroup.com/articles/top-10-mistakes-web-design/","source":"Nielsen Norman Group"},{"title":"End of Web Design","url":"https://www.nngroup.com/articles/end-of-web-design/","source":"Nielsen Norman Group"}],
  graphic: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 567 563\"><g fill=\"none\" fill-rule=\"evenodd\" stroke=\"#f4f1d0\" stroke-width=\"30\"><path style=\"--animation-order: 1\" d=\"M15 98h454v450H15z\"/><path style=\"--animation-order: 2\" d=\"M98 15h454v450H98z\"/></g></svg>",
  sources: ["https://lawsofux.com/jakobs-law/"],
  related: ["mental-model"],
};
