// Generated by scripts/fetch-laws.ts from lawsofux.com and timsommer.be. Do not edit directly.
import type { Law } from "../types";

export const lawOfCommonRegion: Law = {
  slug: "law-of-common-region",
  title: "Law of Common Region",
  definition: "Elements tend to be perceived into groups if they are sharing an area with a clearly defined boundary.",
  category: "theory",
  color: "#249966",
  labels: ["design","psychology","ui"],
  takeaways: ["Common region creates a clear structure and helps users quickly and effectively understand the relationship between elements and sections.","Adding a border around an element or group of elements is an easy way to create common region.","Common region can also be created by defining a background behind an element or group of elements."],
  copy: ["The principles of grouping (or Gestalt laws of grouping) are a set of principles in psychology, first proposed by Gestalt psychologists to account for the observation that humans naturally perceive objects as organized patterns and objects, a principle known as Prägnanz. Gestalt psychologists argued that these principles exist because the mind has an innate disposition to perceive patterns in the stimulus based on certain rules. These principles are organized into five categories: Proximity, Similarity, Continuity, Closure, and Connectedness."],
  source: "https://en.wikipedia.org/wiki/Principles_of_grouping",
  furtherReading: [{"title":"The Principle of Common Region: Containers Create Groupings","url":"https://www.nngroup.com/articles/common-region/","source":"Aurora Harley | Nielsen Norman Group"},{"title":"Design Principles: Visual Perception And The Principles Of Gestalt","url":"https://www.smashingmagazine.com/2014/03/design-principles-visual-perception-and-the-principles-of-gestalt/","source":"Steven Bradley | Smashing Magazine"},{"title":"Gestalt principles","url":"http://www.scholarpedia.org/article/Gestalt_principles","source":"Scholarpedia"}],
  graphic: "<svg viewbox=\"0 0 566 566\" xmlns=\"http://www.w3.org/2000/svg\"><path style=\"--animation-order: 1\" fill-opacity=\".1\" fill=\"#000\" d=\"M0 0h566v566H0z\"/><path style=\"--animation-order: 2\" fill-opacity=\".1\" fill=\"#000\" d=\"M40 40h486v486H40z\"/><path style=\"--animation-order: 3\" fill-opacity=\".1\" fill=\"#000\" d=\"M80 80h406v406H80z\"/><circle style=\"--animation-order: 4\" fill-opacity=\".2\" fill=\"#000\" cx=\"168\" cy=\"168\" r=\"48\"/><circle style=\"--animation-order: 4\" fill-opacity=\".2\" fill=\"#000\" cx=\"284\" cy=\"168\" r=\"48\"/><circle style=\"--animation-order: 4\" fill-opacity=\".2\" fill=\"#000\" cx=\"398\" cy=\"168\" r=\"48\"/><circle style=\"--animation-order: 4\" fill-opacity=\".2\" fill=\"#000\" cx=\"167.209\" cy=\"282.437\" r=\"47.247\"/><circle style=\"--animation-order: 4\" fill=\"#f4f1d0\" cx=\"283.936\" cy=\"282.437\" r=\"47.247\"/><circle style=\"--animation-order: 4\" fill-opacity=\".2\" fill=\"#000\" cx=\"398\" cy=\"282\" r=\"48\"/><circle style=\"--animation-order: 4\" fill-opacity=\".2\" fill=\"#000\" cx=\"168\" cy=\"398\" r=\"48\"/><circle style=\"--animation-order: 4\" fill-opacity=\".2\" fill=\"#000\" cx=\"284\" cy=\"398\" r=\"48\"/><circle style=\"--animation-order: 4\" fill-opacity=\".2\" fill=\"#000\" cx=\"398\" cy=\"398\" r=\"48\"/></svg>",
  sources: ["https://lawsofux.com/law-of-common-region/"],
  related: ["law-of-proximity"],
};
