/**
 * Regenerates the committed curated set-atlas analyses used by the static
 * portfolio and blog figures. The TypeScript compiler cannot run in the
 * browser, so `analyzeSetAtlas` runs here (Node) and the deterministic
 * `AnalyzeResult` payloads are committed as data — the dynamic
 * `SetAtlasVisualization` component renders them at runtime.
 *
 *   bun run nx run set-theory-visualization:generate:curated
 */
import { analyzeSetAtlas, type AnalyzeResult } from "@th-m/knowledge-model";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface CuratedSnippet {
  id: string;
  label: string;
  description: string;
  fileName: string;
  code: string;
}

const snippets: CuratedSnippet[] = [
  {
    id: "traffic-light",
    label: "Traffic light",
    description: "Union and intersection types as overlapping sets of literal values.",
    fileName: "traffic-light.ts",
    code: `type CanCross = "green" | "orange";
type ShouldStop = "orange" | "red";
type TrafficLight = CanCross | ShouldStop;

type WithName = { name: string };
type WithAge = { age: number };
type User = WithName & WithAge;

type Universe = unknown;
type Impossible = string & number;
type EscapeHatch = any;
type Collection<T> = T[];
`,
  },
  {
    id: "typescript-sets",
    label: "TypeScript is set theory",
    description: "The seed workbench: unions, the universe, the empty set, and escape hatches.",
    fileName: "typescript-sets.ts",
    code: `// TypeScript types describe sets of possible values.
// Stop and Caution overlap at "amber"; Signal contains both.
type Stop = "red" | "amber";
type Caution = "amber" | "yellow";
type Go = "green";
type Signal = Stop | Caution | Go;

// The universe, the empty set, and TypeScript's set-breaking escape hatch.
type Everything = unknown;
type Nothing = never;
type EscapeHatch = any;

// An uninstantiated generic is a reusable set template.
type Box<Value> = {
  value: Value;
};
`,
  },
  {
    id: "shared-members",
    label: "Shared members",
    description: "Two unions that overlap on one literal — the simplest overlapping sets.",
    fileName: "shared-members.ts",
    code: `type A = "shared" | "only-a";
type B = "shared" | "only-b";
`,
  },
];

const target = resolve(dirname(fileURLToPath(import.meta.url)), "../src/data/curated-atlases.ts");

const entries: Array<{
  id: string;
  label: string;
  description: string;
  analysis: AnalyzeResult;
}> = [];

for (const snippet of snippets) {
  const analysis = await analyzeSetAtlas({
    revision: 1,
    source: { mode: "snippet", fileName: snippet.fileName, code: snippet.code },
  });
  const errors = analysis.diagnostics.filter(({ severity }) => severity === "error");
  if (errors.length > 0) {
    throw new Error(
      `Curated snippet "${snippet.id}" failed analysis:\n${errors.map(({ message }) => `- ${message}`).join("\n")}`,
    );
  }
  entries.push({
    id: snippet.id,
    label: snippet.label,
    description: snippet.description,
    analysis,
  });
}

const body = `// Generated by scripts/generate-curated-atlases.ts — do not edit by hand.
// Deterministic TypeScript compiler analysis of curated snippets, committed so
// the static portfolio can render set atlases without a compiler in the browser.
import type { AnalyzeResult } from "@th-m/knowledge-model";

export interface CuratedSetAtlasEntry {
  id: string;
  label: string;
  description: string;
  analysis: AnalyzeResult;
}

export const curatedSetAtlasAnalyses: CuratedSetAtlasEntry[] = ${JSON.stringify(entries, null, 2)};
`;

await mkdir(dirname(target), { recursive: true });
await writeFile(target, body);
console.log(`Wrote ${entries.length} curated analyses to ${target}`);
