// Generated by scripts/fetch-laws.ts from lawsofux.com. Do not edit directly.
import type { Law } from "../types";

export const paradoxOfTheActiveUser: Law = {
  slug: "paradox-of-the-active-user",
  title: "Paradox of the Active User",
  definition: "Users never read manuals but start using the software immediately.",
  category: "theory",
  color: "#cfbb28",
  takeaways: ["Users are often motivated to complete their immediate tasks and therefore they don't want to spend time up front reading documentation.","This paradox exist because users will save time in the long term if they take the time to optimize the system and learn more about it.","Make guidance accessible throughout the product experience and design it to fit within the context of use so that it can help these active new users no matter what path they choose to take (e.g. tooltips with helpful information)."],
  copy: ["This concept was first defined by Mary Beth Rosson and John Carroll in 1987 as part of their larger work on interaction design, Interfacing thought: cognitive aspects of human-computer interaction. Rosson and Carroll found that new users were not reading the manuals supplied with computers and instead would just get started using them, even if it meant getting into errors and running into roadblocks."],
  source: "https://www.researchgate.net/publication/262322669_Paradox_of_the_active_user",
  furtherReading: [{"title":"Onboarding for Active Users","url":"https://lawsofux.com/articles/2024/onboarding-for-active-users/","source":"Jon Yablonski | Laws of UX"},{"title":"Paradox of the Active User","url":"https://www.nngroup.com/articles/paradox-of-the-active-user/","source":"Nielsen Norman Group"},{"title":"Paradox of the Active User [PDF]","url":"https://www.researchgate.net/publication/262322669_Paradox_of_the_active_user","source":"ResearchGate"},{"title":"The Paradox of Active Users [PDF]","url":"https://www.researchgate.net/publication/285543245_The_paradox_of_active_users","source":"ResearchGate"}],
  graphic: "<svg viewBox=\"0 0 698 605\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path style=\"--animation-order: 3\" d=\"M58.25 604.696 638.999 604l-232-401.5L348 303 463.392 502.423.0 503 58.25 604.696z\" fill=\"#000\" fill-opacity=\".4\"/><path style=\"--animation-order: 2\" d=\"M697.833 502.595 406.856.0 175.146 401.668 291.681 402.513 406.691 202.869 638.887 603.89 697.833 502.595z\" fill=\"#000\" fill-opacity=\".2\"/><path style=\"--animation-order: 1\" d=\"M289.772.0.0 503.292 463.709 503.124 406.173 401.779 175.772 402 406.968.402014 289.772.0z\" fill=\"#f4f1d0\"/></svg>",
  siteUrl: "https://lawsofux.com/paradox-of-the-active-user/",
  related: ["aesthetic-usability-effect"],
};
