// Generated by scripts/fetch-laws.ts from lawsofux.com. Do not edit directly.
import type { Law } from "../types";

export const parkinsonsLaw: Law = {
  slug: "parkinsons-law",
  title: "Parkinson’s Law",
  definition: "Any task will inflate until all of the available time is spent.",
  category: "theory",
  color: "#97873b",
  takeaways: ["Limit the time it takes to complete a task to what users expect it’ll take.","Reducing the actual duration to complete a task from the expected duration will improve the overall user experience.","Leverage features such as autofill to save the user time when providing critical information within forms. This allows for quick completion of purchases, bookings and other such functions while preventing task inflation."],
  copy: ["Articulated by Cyril Northcote Parkinson as part of the first sentence of a humorous essay published in The Economist in 1955 and since republished online, it was reprinted with other essays in the book Parkinson&rsquo;s Law: The Pursuit of Progress (London, John Murray, 1958). He derived the dictum from his extensive experience in the British Civil Service."],
  source: "https://en.wikipedia.org/wiki/Parkinson%27s_law",
  furtherReading: [{"title":"Parkinson’s Law on Wikipedia","url":"https://en.wikipedia.org/wiki/Parkinson%27s_law","source":"Wikipedia"},{"title":"Parkinson’s Law: Why Constraints Are The Best Thing You Can Work With","url":"https://medium.com/the-mission/parkinsons-law-why-constraints-are-the-best-thing-you-can-work-with-4fad6e0e91cf","source":"Louis Chew | Medium.com"}],
  graphic: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 605 604\"><path style=\"--animation-order: 1\" fill=\"#f4f1d0\" fill-rule=\"nonzero\" stroke=\"#f4f1d0\" stroke-width=\"5\" d=\"M302.854 600.338l-143.63-143.631-49.265 49.264 54.302.048v13.71H86.479v-77.783h13.709l.049 54.302 49.263-49.264L3.747 301.232l142.925-142.924-47.85-47.849-.048 54.302h-13.71V86.979h77.782v13.709l-54.301.049 47.85 47.848L301.439 3.54l145.046 145.045 48.556-48.556-54.302-.048V86.27h77.782v77.783h-13.709l-.049-54.302-48.555 48.556 144.338 144.338-144.338 144.338 49.263 49.264.048-54.302h13.71v77.782h-77.783V506.02l54.302-.048-49.263-49.264-143.631 143.631zM572.26 302.646 301.44 31.825 32.032 301.232l270.822 270.822L572.26 302.646z\"/><circle style=\"--animation-order: 2\" cx=\"302.5\" cy=\"303.5\" r=\"54.5\" fill=\"#000\" fill-opacity=\".2\"/></svg>",
  siteUrl: "https://lawsofux.com/parkinsons-law/",
  related: ["aesthetic-usability-effect"],
};
